jobs:
  - name: job-publish
    public: true
    serial: true
    plan:
    - get: concoursetest-github
      trigger: true

    - task: gen-git-metadata
      file: concoursetest-github/ci/gen_git_metadata.yml

    - put: angrypigs-docker-image
      params:
        build: concoursetest-github
        tag: git-metadata/branch

resources:
  - name: concoursetest-github
    type: git-branch-heads
    source:
      uri: https://github.com/jensendw/concoursetest.git
      branch:
        - release/*
        - develop
        - master
      ignore_paths: [ci/]

  - name: angrypigs-docker-image
    type: docker-image
    source:
      email: {{docker-hub-email}}
      username: {{docker-hub-username}}
      password: {{docker-hub-password}}
      repository: {{docker-hub-image-angrypigs}}

resource_types:
  - name: git-branch-heads
    type: docker-image
    source: {repository: vito/git-branch-heads-resource}
